apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: onlinevideoeditor.azurecr.io/front_end:latest
          ports:
          - containerPort: 80
          env:
            - name: REACT_APP_AUTH0_DOMAIN
              value: onlinevideoeditor.eu.auth0.com
            - name: REACT_APP_AUTH0_CLIENT_ID
              value: UY5hhSigjsOmvkufc4JOZ2ATPBvIQ09Q
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

