apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: public
  tls:
  - hosts:
    - oveapp.samvanhunsel.nl
    secretName: tls-secret
  rules:
  - host: oveapp.samvanhunsel.nl
    http:
      paths:
#      - path: /nodeapp(/|$)(.*)
#        pathType: Prefix
#        backend:
#          service:
#            name: nodesvc
#            port:
#              number: 80
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
