apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects-api
  template:
    metadata:
      labels:
        app: projects-api
    spec:
      containers:
        - name: projects-api
          image: onlinevideoeditor.azurecr.io/onlinevideoeditor:ProjectsApi-893d1e40432aed6bbb206069a91efdc00b3a1bd6
          ports:
          - containerPort: 8080
          env:
#            - name: RABBITMQ_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: rabbitmq-credentials
#                  key: username
#            - name: RABBITMQ_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: rabbitmq-credentials
#                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: projectsapi-database-credentials
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: projectsapi-database-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: projectsapi-database-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: projectsapi-database-credentials
                  key: database
            - name: AZURE_SERVICE_BUS_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: service-bus-credentials
                  key: connection_string
#          env:
#            - name: DB_HOST
#              value: projectsapi-database.postgres.database.azure.com
#            - name: DB_USER
#              value: dbadmin
#            - name: DB_PASSWORD
#              value: dbpassword123!
##              valueFrom:
##                secretKeyRef:
##                  name: secret-keys
##                  key: projectsapi-database-password
#            - name: DB_NAME
#              value: projects
#          volumeMounts:
#            - name: secret-keys
#              mountPath: /mnt/csi/secret-keys
#              readOnly: true
#      volumes:
#        - name: secret-keys
#          csi:
#            driver: secrets-store.csi.x-k8s.io
#            readOnly: true
#            volumeAttributes:
#              secretProviderClass: azure-kvname-wi
#            nodePublishSecretRef:
#              name: 
---
apiVersion: v1
kind: Service
metadata:
  name: projects-api
spec:
  selector:
    app: projects-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
