apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-wi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: 889aa748-ed01-4c77-8c0c-ee32605851dc
    keyvaultName: onlinevideoeditor
    objects:  |
      array:
        - |
          objectName: projectsapi-database-password
          objectType: secret
    tenantId: c66b6765-b794-4a2b-84ed-845b341c086a
