apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects-api
  template:
    metadata:
      labels:
        app: projects-api
    spec:
      containers:
        - name: projects-api
          image: onlinevideoeditor.azurecr.io/projects_api:latest
          ports:
          - containerPort: 8080
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: projectsapi-database-credentials
                  key: host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: projectsapi-database-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: projectsapi-database-credentials
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: projectsapi-database-credentials
                  key: database
            - name: AZURE_SERVICE_BUS_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: service-bus-credentials
                  key: connection_string
            - name: AUTH0_DOMAIN
              value: https://onlinevideoeditor.eu.auth0.com/
---
apiVersion: v1
kind: Service
metadata:
  name: projects-api
spec:
  selector:
    app: projects-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
