name: ApiGateway

on:
  push:
    branches:
      - master
    paths:
      - ApiGateway/**
  workflow_dispatch:
    # Allows for manual build trigger for workflow testing purposes

jobs:
  general-backend-service-pipeline:
    uses: ./.github/workflows/backend-service-base.yaml
    with:
      service-directory: ApiGateway
      csproj-path: ApiGateway.csproj
      image-name: api_gateway
      azure-login-server: onlinevideoeditor.azurecr.io
      deployment-name: api-gateway
    secrets: inherit
