name: MediaService

on:
  push:
    branches:
      - master
    paths:
      - MediaService/**
  workflow_dispatch:
    # Allows for manual build trigger for workflow testing purposes

jobs:
  general-backend-service-pipeline:
    uses: ./.github/workflows/backend-service-base.yaml
    with:
      service-directory: 'MediaService'
      csproj-path: MediaService/MediaService.csproj
      image-name: media_service
      azure-login-server: onlinevideoeditor.azurecr.io
      deployment-name: media-service-api
    secrets: inherit
