name: Service ProjectsApi

on:
  push:
    branches:
      - master
    paths:
      - ProjectsApi/**
  workflow_dispatch:
    # Allows for manual build trigger for workflow testing purposes

jobs:
  call-regular-backend-service-jobs:
    uses: ./.github/workflows/backend-service-base.yaml
    with:
      service-directory: 'ProjectsApi'
      azure-login-server: onlinevideoeditor.azurecr.io
      image-name: projects_api
