name: Service ProjectsApi

on:
  push:
    branches:
      - master
    paths:
      - ProjectsApi/**
  workflow_dispatch:
    # Allows for manual build trigger for workflow testing purposes

jobs:
  general-backend-service-pipeline:
    uses: ./.github/workflows/backend-service-base.yaml
    with:
      service-directory: 'ProjectsApi'
      image-name: projects_api
      azure-login-server: onlinevideoeditor.azurecr.io
    secrets: inherit
