name: Service ProjectsApi

on:
  push:
    branches:
      - master
    paths:
      - front_end/**

env:
  AZURE_CONTAINER_REGISTRY: "onlinevideoeditor"
  CONTAINER_NAME: "ProjectsApi"
  RESOURCE_GROUP: "onlinevideoeditor"
#  CLUSTER_NAME: ""
#  DEPLOYMENT_MANIFEST_PATH: "your-deployment-manifest-path"

jobs:
  release:
#    permissions:
#      contents: read
#      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} .


  #source:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: 
#        uses: 

