name: Service ProjectsApi

on:
  push:
    branches:
      - master
    paths:
      - ProjectsApi/**
  workflow_dispatch:
    # Allows for manual build trigger for workflow testing purposes

env:
  AZURE_LOGIN_SERVER: onlinevideoeditor.azurecr.io
  IMAGE_NAME: projects_api

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
    - run: dotnet format style ApiGateway/ApiGateway.csproj --verify-no-changes --verbosity diagnostic

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
      - run: dotnet test ApiGateway

  release-staging:
    needs: [ unit-test ]
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./ProjectsApi
          tags: ${{ env.AZURE_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ProjectsApi/Dockerfile

  deploy-staging:
    needs: [ release-staging ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: onlinevideoeditor
          cluster-name: online-video-editor
      - name: Bake Kustomize staging overlay
        uses: azure/k8s-bake@v3
        with:
          renderEngine: 'kustomize'
          kustomizationPath: './k8s/overlays/staging'
          kubectl-version: 'latest'
        id: bake
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/k8s-deploy@v4
        with:
          namespace: 'staging'
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: 'onlinevideoeditor.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          pull-images: false

    # kubectl migrate

  acceptance-tests:
    needs: [ deploy-staging ] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: action/checkout@v4

      - uses: actions/setup-dotnet@v4
      - run: dotnet test AcceptanceTests
        env:
          STAGING_BASE_URL: https://oveapp-staging.samvanhunsel.nl

  deploy-production:
     needs: [ acceptance-tests ]
     runs-on: ubuntu-latest
     steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: onlinevideoeditor
          cluster-name: online-video-editor
      - name: Bake Kustomize production overlay
        uses: azure/k8s-bake@v3
        id: bake
        with:
          renderEngine: 'kustomize'
          kustomizationPath: './k8s/overlays/production'
          kubectl-version: 'latest'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: 'onlinevideoeditor.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}'
          pull-images: false
