name: Service ProjectsApi

on:
  push:
    branches:
      - master
    paths:
      - ProjectsApi/**
  workflow_dispatch:
    # Allows for manual build trigger for workflow testing purposes

env:
  AZURE_LOGIN_SERVER: onlinevideoeditor.azurecr.io
  IMAGE_NAME: projects_api

jobs:
  call-regular-backend-service-jobs:
    uses: ./.github/workflows/backend-service-base.yaml
    with:
      service-directory: 'ProjectsApi'
      azure-login-server: ${{ env.AZURE_LOGIN_SERVER }}
      image-name: projects_api
