name: Service VideoRenderWorker

on:
  push:
    branches:
      - master
    paths:
      - VideoRenderWorker/**
  workflow_dispatch:
    # Allows for manual build trigger for workflow testing purposes

jobs:
  general-backend-service-pipeline:
    uses: ./.github/workflows/backend-service-base.yaml
    with:
      service-directory: VideoRenderWorker
      csproj-path: VideoRenderWorker/VideoRenderWorker.csproj
      image-name: video_render_worker
      azure-login-server: onlinevideoeditor.azurecr.io
      deployment-name: video-render-worker
    secrets: inherit
