name: Service video_render_worker

on:
  push:
    branches:
      - master
    paths:
      - video_render_worker/**

env:
  AZURE_LOGIN_SERVER: onlinevideoeditor.azurecr.io
  SERVICE_NAME: video_render_worker

jobs:
  release:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./${{ env.SERVICE_NAME }}
          tags: ${{ env.AZURE_LOGIN_SERVER }}/onlinevideoeditor:${{ env.SERVICE_NAME }}-${{ github.sha }}
          file: ${{ env.SERVICE_NAME }}/Dockerfile
