apiVersion: v1
kind: Secret
metadata:
  name: media-service-api-database-credentials
type: Opaque
data:
  host: c3RhZ2luZy1kYXRhYmFzZS5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb20=
  username: ZGJ1c2Vy
  password: ZGJwYXNzd29yZDEyMyE=
  database: bWVkaWE=
